apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # user
  db_user: dXNlcg==
  # pass
  db_pwd: cGFzcw==
  # app-db
  db_name: YXBwLWRi
  # root-pass
  db_root_pwd: cm9vdC1wYXNz
