apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: java-app-ingress
spec:
  ingressClassName: nginx
  rules:
    # no host -> matches every Host header, so the app is reachable
    # directly via the ELB IP: http://<ELB-IP>/get-data
    - http:
        paths:
          - backend:
              service:
                name: java-app-service
                port:
                  number: 8080
            path: /
            pathType: Prefix
