apiVersion: v1
kind: Secret
metadata:
  name: rocketchat-admin
  namespace: monitoring
type: Opaque
stringData:
  ADMIN_USERNAME: admin
  ADMIN_EMAIL: admin@example.com
  ADMIN_PASS: CHANGE_ME
  OVERWRITE_SETTING_Show_Setup_Wizard: "completed"
